spring.application.name=FakeNewsDetector

# Run Spring Boot on a different port (instead of 8080)
server.port=9090

# Oracle 10g XE connection
spring.datasource.url=jdbc:oracle:thin:@127.0.0.1:1521:XE
spring.datasource.username=system
spring.datasource.password=system
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# JPA & Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

